Repository codebuster22/ipvc-dapp, pull requests merged in 2021-08, with the labels that each got.

#26 fix/refactor
  .eslintrc.js
  pages/_app.js
  pages/index.tsx
  pages/login/index.tsx
  pages/onboarding/index.tsx
  pages/warrior/index.tsx
  src/api/mutations.ts
  src/api/queries.ts
  src/components/Box.tsx
  src/components/Text.tsx
  src/components/Warrior.tsx
  src/containers/Login/index.tsx
  src/containers/Onboarding/index.new.tsx
  src/containers/Onboarding/index.tsx
  src/containers/Warrior/index.tsx
  src/ethereum/utils/generateWarrior.ts
  src/utils/helpers.ts
  src/utils/parsing.ts
  tsconfig.json
Labels: Ready

#25 feat/Gallery page
  package-lock.json
  package.json
  pages/_app.js
  pages/gallery/index.tsx
  src/components/Warrior.tsx
  src/components/hooks/useRegistry.tsx
  src/containers/Onboarding/index.new.tsx
  src/containers/Onboarding/index.tsx
  src/containers/Warrior/index.tsx
  src/containers/gallery/index.tsx
  src/contracts/contracts.json
  src/utils/constants.ts
Labels: in progress

#28 Chore : Incorporated mint fee for the generate warrior transaction
  src/ethereum/utils/generateWarrior.ts
Labels: help wanted
